# Site title and subtitle. This is used in _includes/header.html
title: 'AbanteCart - Open Source Ecommerce Platform Documentations'
subtitle: ''

# if you use google analytics, add your tracking id here
google_analytics_id: 'UA-26192520-5'

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/abantecart/abantecart.github.io'

# Default categories (in order) to appear in the navigation
sections: [
    ['user_manual', 'User Manuals'],
    ['developer_api', 'Developers API']
]

baseurl: "http://abantecart.github.io/"
permalink: pretty

# Syntax highlighting
highlighter: pygments

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

gems:
  - jekyll-redirect-from